### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [jgf/smali-analysis#1]
Hi
The following lines have cryptographic API misuses. <br> File name => dexlib/src/main/java/org/jf/dexlib/DexFile.java: Line number => 878: API name => MessageDigest:<BR> File name => dexlib/src/main/java/org/jf/dexlib/DexFile.java: Line number => 870: API name => MessageDigest:First parameter (with value "SHA-1") should be any of {SHA-256, SHA-384, SHA-512}<BR>

**Comment by jgf** [comment]
Sorry thats neither a misuse nor very helpful. Please review manually before you create issues and do not rely solely on automated static code analysis - I know that first hand...

You recently created 924 similar issues on other repos.
